# Generated by Django 4.2.14 on 2024-07-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('address', models.JSONField()),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('hotel_class', models.FloatField()),
                ('details', models.JSONField()),
                ('type', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ratings', models.JSONField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.JSONField()),
                ('date_stayed', models.CharField(max_length=50)),
                ('offering_id', models.IntegerField()),
                ('num_helpful_votes', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('via_mobile', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelsapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelOverallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_id', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('average_overall_rating', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_ratings', to='hotelsapp.hotel')),
            ],
        ),
    ]
